#+STARTUP: showall
#+OPTIONS: toc:nil
#+title: JAIF 2020

* Inscription



# [2019-05-16 jeu.]
# *Les inscriptions sont closes.  Contactez le comité de programme.*

# La journée est gratuite mais les inscriptions sont obligatoires et le
# nombre de participants est limité à la capacité d'accueil de la salle.
# Les inscriptions seront closes dès que la capacité d'accueil de la
# salle sera atteinte, et au plus tard le 10 mars.

# [[https://framaforms.org/jaif-2020-inscription-1579194393][Pour vous inscrire, complétez le formulaire à cette adresse]].

# *Si vous ne pouvez plus participer après inscrition, merci de nous en
# faire part rapidement*.
# Ceci nous permettra de mieux calibrer la logistique de la journée.


** Report de la journée

Le comité d'organisation de JAIF 2020 a décidé de *reporter la
journée* prévue initialement le 18 mars à une date ultérieure, très
probablement début septembre 2020.  Cette décision n'a pas été
facile. Elle a été motivée par une série de facteurs arrivés en
cascade :

   + impossibilité de certains orateurs de venir pour raison
     d'interdication de voyage et/ou de participation à des conférences
     de la part de leur employeur ;
   + même problème parmi l'auditoire, problème accentué par les
     restrictions des déplacements entre les différentes régions.

  Nous souhaitons que cette journée JAIF 2020 soit un lieu
d'information et d'échange riche. Pour cette raison, nous pensons que
l'impact maximal aura lieu à une période plus propice à une grande
participation. Le format de la journée sera préservé : il s'agit d'un
report "toutes choses égales par ailleurs".

Dès que nous aurons plus d'informations, nous vous communiquerons la
nouvelle date de JAIF 2020 dans les semaines à venir, via les adresses
mail des personnes déjà inscrites et via les canaux de diffusion
habituels (listes GdR, etc.).


Contact: [[mailto:jaif@saxifrage.saclay.cea.fr?subject=%5Binscription%5D][jaif@saxifrage.saclay.cea.fr]]
